spring:
  application:
    name: Spring Boot estudos

  # H2 Connection
  datasource:
    url: jdbc:h2:mem:categoria
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 Client
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA / Hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
