spring:
  application:
    name: campeonato

  profiles:
    active: test
---
# TEST (profile "test")
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:campeonato
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:import.sql
      schema-locations: classpath:schema.sql
